# Sequentielles Neuronales Netzwerk

Lineare Neuronale Netzwerke bringen schon einiges an Funktionen; sie können aber nur als _lineare Klassifizierer_ verwendet werden. Neuronale Nezwerke erhalten ihre Durchschlagskraft erst durch das Vorhandensein __verborgener Schichten__ (_hidden layers_).

In `PyTorch` werden Netzwerke mit verborgenen Schichten durch Zusammenschalten Linearer Netzwerke erzielt, deren Ausgangsneuronen die Eingangsneuronen der nächsten Schicht bilden.

In [1]:
import torch
import torch.nn as nn

In [9]:
n_features, n_classes = 8, 2
sequential = nn.Sequential(
    nn.Linear(n_features, 4),
    nn.Linear(4, n_classes)
)

Die Anzahl der Parameter (Gewichte und Bias) wird _model capacity_ genannt. Die Methode `numel()`gibt die Anzahl der Parameter eines tensors  zurück:

In [17]:
total = 0
for p in sequential.parameters():
    print(p,p.numel())
    total += p.numel()
print(total)

Parameter containing:
tensor([[ 0.1919,  0.2773, -0.1742, -0.2454, -0.0268,  0.0849, -0.2819,  0.2359],
        [-0.2245, -0.3110,  0.3090, -0.1731, -0.0224, -0.1219, -0.2058, -0.1174],
        [ 0.1164, -0.1399,  0.3104, -0.0597,  0.0412, -0.2646,  0.0370, -0.2347],
        [-0.1672,  0.3428,  0.1552,  0.2147,  0.0731,  0.1483, -0.1882,  0.0923]],
       requires_grad=True) 32
Parameter containing:
tensor([-0.0004,  0.2606,  0.0739, -0.2238], requires_grad=True) 4
Parameter containing:
tensor([[ 0.1194, -0.0531, -0.3539,  0.0356],
        [-0.4885,  0.0291, -0.0663, -0.1487]], requires_grad=True) 8
Parameter containing:
tensor([ 0.3250, -0.1834], requires_grad=True) 2
46


Wir wenden das Netzwerk auf den Tensor an und erhalten den Ausgabetensor: