# Lineares Neuronales Netzwerk

Als einfachstes beispiel für ein Neuronales Netzwerk in `PyTorch` demonstrieren wir ein vollständig vernetztes lineares Netzwerk mit zwei Schichten.



In [1]:
import torch
import torch.nn as nn

### Aufbau eines Linear NN

Zur Erzeugung geben wir die Anzahl der Eingabeneuronen sowie die Anzahl der Ausgabeneuronen an. Diese sind immer durch das Problem definiert: Die Anzahl der Eingabeneuronen entspricht der Anzahl der __Features__ und die Anzahl der Ausgabeneuronen  der Anzahl der __Klassen__.

Wenn die Eingangdaten über drei Features verfügen und in zwei Klassen aufgeteilt werden sollen, so definieren wir ein lineares NN wir folgt:

In [ ]:
linear_layer = nn.Linear(in_features = 3, out_features = 2)

Die Gewichte bilden einen zufällig generierten Tensor:

In [6]:
print(f'Gewichte: {linear_layer.weight}\nBias: {linear_layer.bias}')

Gewichte: Parameter containing:
tensor([[ 0.0777, -0.4408, -0.4832],
        [-0.5636, -0.3881,  0.2319]], requires_grad=True)
Bias: Parameter containing:
tensor([0.1906, 0.3484], requires_grad=True)


Der Gewichtstensor ist eine 2x3-Matrix. Sowohl bei ihm als auch beim Bias ist `required_grad` aktiviert, damit eine Backpropagation möglich ist.

Wir erstellen einen Eingabe-Tensor mit drei Features:

In [8]:
input = torch.tensor([[0.374, 0.4547, -0.2356]])

Wir wenden das Netzwerk auf den Tensor an und erhalten den Ausgabetensor:

In [9]:
output = linear_layer(input)
output

tensor([[ 0.1331, -0.0935]], grad_fn=<AddmmBackward0>)