# Lineares Neuronales Netzwerk

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/infaktum/dl1/03_Deep_Learning/PT03.1.1_Linear_NN.ipynb)

Als einfachstes Beispiel für ein Neuronales Netzwerk in `PyTorch` demonstrieren wir ein vollständig verbundenes (_fully connected_) lineares Netzwerk mit zwei Schichten.

In [1]:
import torch
import torch.nn as nn

### Aufbau eines Linear NN

Zur Erzeugung geben wir die Anzahl der Eingabeneuronen sowie die Anzahl der Ausgabeneuronen an. Diese sind immer durch das Problem definiert: Die Anzahl der Eingabeneuronen entspricht der Anzahl der __Features__ und die Anzahl der Ausgabeneuronen  der Anzahl der __Klassen__.

Wenn die Eingangdaten über drei Features verfügen und in zwei Klassen aufgeteilt werden sollen, so definieren wir ein lineares NN wir folgt:

In [2]:
fc = nn.Linear(in_features = 3, out_features = 2)

Die Gewichte bilden einen zufällig generierten Tensor:

In [8]:
print(f'Netzwerk: {fc}\nGewichte: {fc.weight}\nBias: {fc.bias}')

Netzwerk: Linear(in_features=3, out_features=2, bias=True)
Gewichte: Parameter containing:
tensor([[-0.4004,  0.1939,  0.2568],
        [-0.5047, -0.1425, -0.0705]], requires_grad=True)
Bias: Parameter containing:
tensor([ 0.4323, -0.0508], requires_grad=True)


Der Gewichtstensor ist eine 2x3-Matrix. Sowohl bei ihm als auch beim Bias ist `required_grad` aktiviert, damit eine Backpropagation möglich ist.

Wir erstellen einen Eingabe-Tensor mit drei Features:

In [9]:
input = torch.tensor([[0.374, 0.4547, -0.2356]])

Wir wenden das Netzwerk auf den Tensor an und erhalten den Ausgabetensor:

In [10]:
output = fc(input)
output

tensor([[ 0.3102, -0.2877]], grad_fn=<AddmmBackward0>)