# Tensoren

__Tensoren__ sind die zentrale Datenstruktur in `PyToch`. Sie stehen für die im Deep Learning verwendeten __Vektoren__, __Matrizen__ und anderer Objekte als Zusammenfassung reeller Daten in eine Struktur beliebiger Dimension (_Stufen_), die durch zahlreiche mathematische Operationen manipuliert werden können.

Auch die Python-Bibliothek `NumPy` arbeitet mit Tensoren; dort werden sie allerdings `ndarray`(_n-dimensionales Array_) genannt. Wer `NumPy` und seine `ndarrays` kennt, wird die meisten Eigenschaften von  `PyTorchs` Tensoren wiedererkennen.

### Unterschiede zu `NumPy`

Die Tensoren in `PyTorch` haben zwei wesentliche zusätzliche Eigenschaften gegenüber den ndarrays in `NumPy`:

* __Unterstützung von GPUs__: Tensoren können auf GPUs "verschoben" werden, so dass mathematische Operationen darauf parallelisiert und beschleunigt werden können. Die fehlende Unterstützung für GPUs ist die größte Schwäche von `NumPy`.
* __Automatisierte Gradientenberechnung__: Tensoren in `PyTorch` ermöglichen die Automatisierung der Gradientenbildung bei Transformationen. Da der Gradientenabstieg die Basis beim Lernprozess neuronaler Netzwerke bildet, ist dies eine große Hilfe beim Deep Leraning, selbst wenn keine GPU zur Verfügung steht.



<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>Anmerkung</strong></div>

<div style = "background-color: #eeeeee;padding:10px">
In der Physik sind Tensoren ebenfalls wichtige Hilfsmittel, unterscheiden sich allerdings in ihrer Bedeutung erheblich von Tensoren in der KI.
</div>



## Erzeugung von Tensoren

### Erzeugung aus Python-Lsten

Wie bei `NumPy` können Tensoren einfach durch die Übergabe eine mehrdimensionalen Python-Liste erzeugt werden:

In [2]:
import torch

In [18]:
skalar = torch.tensor(1)
vektor = torch.tensor([1,2,3])
matrix = torch.tensor([[1,2,3],[4,5,6]])

print(f'Sakalar: {skalar}\nVektor: {vektor}\nMatrix: {matrix}')


Sakalar: 1
Vektor: tensor([1, 2, 3])
Matrix: tensor([[1, 2, 3],
        [4, 5, 6]])


### Erzeugung aus `NumPy`-Arrays

Die Konvertierung von `Numpy`-Arrays in `PyTorch`-Tensoren und zurück ist ebenfalls sehr einfach:

In [3]:
import numpy as np

array = np.arange(1,3)
tensor = torch.tensor(array)
t_array = tensor.numpy()

print(f'Tensor: {tensor}\nndarray: {t_array}')

Tensor: tensor([1, 2])
ndarray: [1 2]


### Datentyp

Der Datentyp des Tensors kann explizit gesetzt werden. Dabei werden die definierten Datentypen aus dem Paket `torch` verwendet (und ggf. dahin konvertiert):

In [29]:
tensor = torch.tensor([1,2,3], dtype=float)
print(f'Tensor: {tensor}, Datentyp: {tensor.dtype}')

Tensor: tensor([1., 2., 3.], dtype=torch.float64), Datentyp: torch.float64


### Routinen zur Erzeugung von Tensoren

Darüber hinaus existieren in `PyTorch` viele weitere Routinen zur Erzeugung von Tensoren. Einige sind aus `NumPy`bekannt: 

In [48]:
t0 = torch.zeros(2,2)
t1 = torch.ones(2,2)
t_id = torch.eye(2,2)

m1 = torch.empty(2,2) 

t0, t1, t_id, m1

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 0.],
         [0., 1.]]),
 tensor([[ 0.5331,  0.2098],
         [ 0.8360, -1.5216]]),
 tensor([[1.0000e+00, 1.0000e+00],
         [0.0000e+00, 1.1914e-05]]))

Zufällig erzeugte Tensoren:

In [8]:
t_rand = torch.rand(4)
t_rand_normal = torch.randn(4)
t_rand_int = torch.randint(3,8,(4,))

t_rand, t_rand_normal, t_rand_int

(tensor([0.9305, 0.9099, 0.8776, 0.3480]),
 tensor([0.2144, 0.7572, 0.3071, 0.4491]),
 tensor([5, 7, 4, 4]))

### Tensor-Arithmetik

`PyTorch` unterstützt wie `NumPy` die Arithmetik von Vektoren und Matrizen:

* Addition von Vektoren
* Multiplikation von Skalaren mit Vektoren und Matrizen
* Multiplikation von Matrizen mit Vektoren und anderen Matrizen
* Skalarprodukte von Vektoren
* Transponieren von Tensoren

In [39]:
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])

m1 = torch.tensor([[1,2,3],[4,5,6]])
m2 = torch.tensor([[1,2,3],[4,5,6]])

In [45]:
v1 + v2, 3 * v1, v1.T @ v2

(tensor([5, 7, 9]), tensor([3, 6, 9]), tensor(32))

In [43]:
m1 @ v1
m1 @ m2.T

tensor([[14, 32],
        [32, 77]])